baseURL = 'https://Danielvima.github.io/'
languageCode = 'en-us'
title = 'Daniel Villalobos'
theme = "PaperMod"

defaultContentLanguage = "en"


[params.assets]
  favicon = "images/favicon.ico"

[params.label]
  text = "Daniel Villalobos"
  icon = "images/logoB.png"
  iconHeight = 40

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Proyectos"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url = "/contact/"
    weight = 3

[languages]
[languages.es]
  languageName = "Español"
  weight = 1

[languages.en]
  languageName = "English"
  weight = 2